Repository cb-geo/mpm-point-generator, pull requests merged in 2019-02, with the labels that each got.

#74 :scroll: License and DCO
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  dco.md
  license.md
Labels: Priority: Low

#73 Write mesh file for mpm input
  bin/box.msh
  bin/cube.json
  include/gmsh.tcc
  include/mesh.h
  include/mesh.tcc
  src/main.cc
  tests/gmsh_test_3d.cc
Labels: Priority: High, Status: Review needed, Type: Feature request, Type: Validation

#75 :hammer: Fix the 2D GMSH reading test
  .circleci/config.yml
  include/gmsh.tcc
  tests/gmsh_test_2d.cc
  tests/gmsh_test_3d.cc
Labels: Priority: Medium, Status: In progress, Status: Revision needed, Type: Enhancement
